services:
  pigeon-pod:
    build: .
    image: pigeon-pod:latest
    restart: unless-stopped
    container_name: pigeon-pod
    ports:
      - '8834:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/pigeon-pod.db
      - PIGEON_LOG_FILE=/data/logs/pigeon-pod.log
      - PIGEON_YT_DLP_PO_TOKEN_PROVIDER_URL=http://bgutil-provider:4416
    depends_on:
      - bgutil-provider
    volumes:
      - pigeon-pod-data:/data

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:1.3.1-deno
    restart: unless-stopped

volumes:
  pigeon-pod-data:
