package top.asimov.pigeon.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.baomidou.mybatisplus.annotation.FieldStrategy;
import com.baomidou.mybatisplus.annotation.TableField;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import top.asimov.pigeon.config.StorageProperties;
import top.asimov.pigeon.helper.CookieSessionLocks;
import top.asimov.pigeon.mapper.CookieConfigMapper;
import top.asimov.pigeon.model.entity.CookieConfig;
import top.asimov.pigeon.model.enums.CookiePlatform;
import top.asimov.pigeon.model.enums.CookieSessionStatus;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class CookieServiceTest {

  private static final String STORED_COOKIES = String.join("\n",
      "# Netscape HTTP Cookie File",
      "# Generated by the user, do not edit.",
      "",
      "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tLOGIN_INFO\tlogin-value",
      ".youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsapisid-value",
      ".youtube.com\tTRUE\t/\tTRUE\t1850000000\t__Secure-1PSIDTS\told-1psidts");

  /**
   * Reproduces the file yt-dlp actually writes back: its own header, no {@code #HttpOnly_}
   * prefixes, its own injected cookies, and the credentials YouTube cleared simply missing.
   */
  private static final String YTDLP_WRITE_BACK = String.join("\n",
      "# Netscape HTTP Cookie File",
      "# This file is generated by yt-dlp.  Do not edit.",
      "",
      ".youtube.com\tTRUE\t/\tTRUE\t1950000000\t__Secure-1PSIDTS\trefreshed-1psidts",
      ".youtube.com\tTRUE\t/\tFALSE\t0\tPREF\thl=en&tz=UTC",
      ".youtube.com\tTRUE\t/\tTRUE\t1950000000\tVISITOR_INFO1_LIVE\tvisitor-value");

  @Mock
  private CookieConfigMapper cookieConfigMapper;

  @TempDir
  Path tempDir;

  private CookieConfig storedConfig;
  private CookieService cookieService;

  @BeforeEach
  void setUp() {
    StorageProperties storageProperties = new StorageProperties();
    storageProperties.setTempDir(tempDir.toString());

    storedConfig = CookieConfig.builder()
        .id(1L)
        .platform(CookiePlatform.YOUTUBE.name())
        .cookiesContent(STORED_COOKIES)
        .enabled(true)
        .sourceType(CookieService.SOURCE_TYPE_UPLOAD)
        .sessionStatus(CookieSessionStatus.ACTIVE.name())
        .autoRefreshEnabled(true)
        .rotateFailureCount(0)
        .updatedAt(LocalDateTime.now().minusMinutes(10))
        .build();

    when(cookieConfigMapper.selectOne(any())).thenAnswer(invocation -> storedConfig);
    doAnswer(invocation -> 1).when(cookieConfigMapper).updateById(any(CookieConfig.class));

    cookieService = new CookieService(cookieConfigMapper, storageProperties,
        new CookieSessionLocks());
  }

  @Test
  void snapshotWritesTheStoredJarToADedicatedFile() throws IOException {
    CookieService.CookieSnapshot snapshot =
        cookieService.createTempCookiesSnapshot(CookiePlatform.YOUTUBE, "0");

    assertNotNull(snapshot);
    assertEquals(CookiePlatform.YOUTUBE, snapshot.platform());
    assertEquals(STORED_COOKIES,
        Files.readString(Path.of(snapshot.filePath()), StandardCharsets.UTF_8));
  }

  @Test
  void writeBackTakesTheFreshTokenButKeepsCredentialsHeaderAndHttpOnlyPrefixes() throws IOException {
    CookieService.CookieSnapshot snapshot = writeSnapshotFile(YTDLP_WRITE_BACK);

    cookieService.mergeYtDlpWriteBack(snapshot);

    String merged = storedConfig.getCookiesContent();
    assertTrue(merged.contains("__Secure-1PSIDTS\trefreshed-1psidts"));
    assertTrue(merged.contains("#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tLOGIN_INFO\tlogin-value"));
    assertTrue(merged.contains("SAPISID\tsapisid-value"));
    assertTrue(merged.startsWith("# Netscape HTTP Cookie File\n# Generated by the user"));
    assertEquals(CookieService.SOURCE_TYPE_YTDLP_WRITEBACK, storedConfig.getSourceType());
  }

  @Test
  void writeBackNeverImportsCookiesYtDlpInjectedItself() throws IOException {
    CookieService.CookieSnapshot snapshot = writeSnapshotFile(YTDLP_WRITE_BACK);

    cookieService.mergeYtDlpWriteBack(snapshot);

    assertTrue(!storedConfig.getCookiesContent().contains("PREF"));
    assertTrue(!storedConfig.getCookiesContent().contains("VISITOR_INFO1_LIVE"));
  }

  @Test
  void writeBackIsDiscardedWhenTheStoreWasRefreshedDuringTheDownload() throws IOException {
    CookieService.CookieSnapshot snapshot = writeSnapshotFile(YTDLP_WRITE_BACK);
    storedConfig.setUpdatedAt(LocalDateTime.now().plusMinutes(1));

    cookieService.mergeYtDlpWriteBack(snapshot);

    assertEquals(STORED_COOKIES, storedConfig.getCookiesContent());
    verify(cookieConfigMapper, never()).updateById(any(CookieConfig.class));
  }

  @Test
  void writeBackWithoutChangesDoesNotTouchTheStore() throws IOException {
    CookieService.CookieSnapshot snapshot = writeSnapshotFile(STORED_COOKIES);

    cookieService.mergeYtDlpWriteBack(snapshot);

    assertEquals(STORED_COOKIES, storedConfig.getCookiesContent());
    verify(cookieConfigMapper, never()).updateById(any(CookieConfig.class));
  }

  @Test
  void uploadResetsThePreviousSessionVerdict() {
    storedConfig.setSessionStatus(CookieSessionStatus.INVALID.name());
    storedConfig.setRotateFailureCount(3);
    storedConfig.setLastFailureReason("HTTP_403");
    storedConfig.setNextRotateAt(LocalDateTime.now().plusHours(1));

    cookieService.upsert(CookiePlatform.YOUTUBE, STORED_COOKIES);

    assertEquals(CookieSessionStatus.UNKNOWN.name(), storedConfig.getSessionStatus());
    assertEquals(0, storedConfig.getRotateFailureCount());
    assertEquals(null, storedConfig.getLastFailureReason());
    assertEquals(null, storedConfig.getNextRotateAt());
    assertEquals(CookieService.SOURCE_TYPE_UPLOAD, storedConfig.getSourceType());
  }

  @Test
  void summaryExposesSessionStateWithoutTheCookieContent() {
    storedConfig.setSessionStatus(CookieSessionStatus.ACTIVE.name());
    when(cookieConfigMapper.selectList(any())).thenReturn(java.util.List.of(storedConfig));

    var summaries = cookieService.listSummaries();

    assertEquals(1, summaries.size());
    assertEquals("YOUTUBE", summaries.get(0).getPlatform());
    assertEquals(CookieSessionStatus.ACTIVE.name(), summaries.get(0).getSessionStatus());
    assertTrue(summaries.get(0).getAutoRefreshEnabled());
    assertTrue(!summaries.get(0).toString().contains("login-value"));
  }

  /**
   * Clearing a session field has to reach the database. MyBatis-Plus skips null fields on update by
   * default, which silently leaves a stale failure reason or schedule behind after a fresh upload,
   * and a mocked mapper cannot catch that.
   */
  @Test
  void nullableSessionFieldsAreWrittenBackEvenWhenCleared() throws NoSuchFieldException {
    for (String fieldName : java.util.List.of("lastRotatedAt", "nextRotateAt", "lastCheckedAt",
        "lastFailureReason")) {
      TableField annotation = CookieConfig.class.getDeclaredField(fieldName)
          .getAnnotation(TableField.class);
      assertNotNull(annotation, fieldName + " must declare an update strategy");
      assertEquals(FieldStrategy.ALWAYS, annotation.updateStrategy(),
          fieldName + " must be written back even when null");
    }
  }

  private CookieService.CookieSnapshot writeSnapshotFile(String content) throws IOException {
    Path file = tempDir.resolve("cookies_youtube_0_write_back.txt");
    Files.writeString(file, content, StandardCharsets.UTF_8);
    return new CookieService.CookieSnapshot(CookiePlatform.YOUTUBE, file.toString(),
        LocalDateTime.now());
  }
}
