package top.asimov.pigeon.util;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.junit.jupiter.api.Test;

class NetscapeCookieFileTest {

  private static final long NOW = 1_800_000_000L;

  private static final String USER_UPLOADED_FILE = String.join("\n",
      "# Netscape HTTP Cookie File",
      "# Generated by the user, do not edit.",
      "",
      "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tLOGIN_INFO\tlogin-value",
      ".youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsapisid-value",
      ".youtube.com\tTRUE\t/\tTRUE\t1900000000\t__Secure-1PSID\tpsid-value",
      ".youtube.com\tTRUE\t/\tTRUE\t1850000000\t__Secure-1PSIDTS\told-1psidts",
      ".google.com\tTRUE\t/\tTRUE\t1850000000\t__Secure-1PSIDTS\told-1psidts",
      "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\tYSC\tsession-value");

  @Test
  void roundTripPreservesCommentsBlankLinesAndHttpOnlyPrefixes() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    assertEquals(USER_UPLOADED_FILE, file.serialize());
    assertEquals(6, file.cookies().size());
  }

  @Test
  void parsesSessionCookiesAndHttpOnlyFlag() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookie loginInfo = findCookie(file, "LOGIN_INFO");
    assertTrue(loginInfo.httpOnly());
    assertFalse(loginInfo.isSessionCookie());

    NetscapeCookie ysc = findCookie(file, "YSC");
    assertTrue(ysc.isSessionCookie());
  }

  @Test
  void keepsUnparseableLinesVerbatim() {
    String content = String.join("\n",
        "# Netscape HTTP Cookie File",
        "this line is not a cookie",
        ".youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsapisid-value");

    NetscapeCookieFile file = NetscapeCookieFile.parse(content);

    assertEquals(1, file.cookies().size());
    assertEquals(content, file.serialize());
  }

  @Test
  void detectsYoutubeAuthCookies() {
    assertTrue(NetscapeCookieFile.parse(USER_UPLOADED_FILE).hasYoutubeAuthCookies());

    String withoutLoginInfo = String.join("\n",
        "# Netscape HTTP Cookie File",
        ".youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsapisid-value");
    assertFalse(NetscapeCookieFile.parse(withoutLoginInfo).hasYoutubeAuthCookies());

    String withoutSapisid = String.join("\n",
        "# Netscape HTTP Cookie File",
        "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tLOGIN_INFO\tlogin-value");
    assertFalse(NetscapeCookieFile.parse(withoutSapisid).hasYoutubeAuthCookies());
  }

  @Test
  void cookieHeaderPrefersYoutubeDomainAndSkipsMissingNames() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    String header = file.toCookieHeader(NetscapeCookieFile.rotationRequestCookieNames());

    assertEquals("__Secure-1PSID=psid-value; __Secure-1PSIDTS=old-1psidts", header);
  }

  @Test
  void mergeUpdatesEveryDomainHoldingTheRotatedCookie() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookieFile.MergeResult result = file.merge(
        List.of(cookie(".google.com", "__Secure-1PSIDTS", "new-1psidts", NOW + 3600)),
        NetscapeCookieFile.rotatableCookieNames(), NOW);

    assertTrue(result.changed());
    assertEquals(List.of("__Secure-1PSIDTS"), result.updatedNames());
    assertEquals(List.of(".youtube.com", ".google.com"), result.updatedDomains());
    assertTrue(result.file().serialize().contains(
        ".youtube.com\tTRUE\t/\tTRUE\t" + (NOW + 3600) + "\t__Secure-1PSIDTS\tnew-1psidts"));
    assertTrue(result.file().serialize().contains(
        ".google.com\tTRUE\t/\tTRUE\t" + (NOW + 3600) + "\t__Secure-1PSIDTS\tnew-1psidts"));
  }

  @Test
  void mergeAddsUnknownRotatableCookieOnItsOwnDomain() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookieFile.MergeResult result = file.merge(
        List.of(cookie(".google.com", "__Secure-3PSIDTS", "fresh-3psidts", NOW + 3600)),
        NetscapeCookieFile.rotatableCookieNames(), NOW);

    assertTrue(result.changed());
    assertEquals(7, result.file().cookies().size());
    assertEquals("fresh-3psidts", findCookie(result.file(), "__Secure-3PSIDTS").value());
  }

  @Test
  void mergeIgnoresCookiesOutsideTheRotatableWhitelist() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookieFile.MergeResult result = file.merge(
        List.of(cookie(".youtube.com", "__Secure-1PSID", "attacker-value", NOW + 3600)),
        NetscapeCookieFile.rotatableCookieNames(), NOW);

    assertFalse(result.changed());
    assertEquals(List.of("__Secure-1PSID"), result.rejectedNames());
    assertEquals("psid-value", findCookie(result.file(), "__Secure-1PSID").value());
  }

  @Test
  void mergeIgnoresDeletionInstructions() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookieFile.MergeResult result = file.merge(
        List.of(
            cookie(".youtube.com", "__Secure-1PSIDTS", "", NOW + 3600),
            cookie(".youtube.com", "__Secure-3PSIDTS", "expired", NOW - 10)),
        NetscapeCookieFile.rotatableCookieNames(), NOW);

    assertFalse(result.changed());
    assertEquals("old-1psidts", findCookie(result.file(), "__Secure-1PSIDTS").value());
    assertFalse(result.file().hasCookie("__Secure-3PSIDTS"));
  }

  @Test
  void mergeIsANoOpWhenValuesDidNotChange() {
    NetscapeCookieFile file = NetscapeCookieFile.parse(USER_UPLOADED_FILE);

    NetscapeCookieFile.MergeResult result = file.merge(
        List.of(cookie(".youtube.com", "__Secure-1PSIDTS", "old-1psidts", 1850000000L)),
        NetscapeCookieFile.rotatableCookieNames(), NOW);

    assertFalse(result.changed());
    assertEquals(USER_UPLOADED_FILE, result.file().serialize());
  }

  /**
   * Reproduces the yt-dlp write-back observed in practice: it drops the {@code #HttpOnly_}
   * prefixes, replaces the header, injects its own cookies and omits the credentials YouTube
   * cleared. Merging must take only the freshness token from it.
   */
  @Test
  void mergeOfYtDlpWriteBackKeepsCredentialsAndRejectsInjectedCookies() {
    NetscapeCookieFile stored = NetscapeCookieFile.parse(USER_UPLOADED_FILE);
    NetscapeCookieFile ytDlpDump = NetscapeCookieFile.parse(String.join("\n",
        "# Netscape HTTP Cookie File",
        "# This file is generated by yt-dlp.  Do not edit.",
        "",
        ".youtube.com\tTRUE\t/\tTRUE\t" + (NOW + 7200) + "\t__Secure-1PSIDTS\trefreshed-by-ytdlp",
        ".youtube.com\tTRUE\t/\tFALSE\t0\tPREF\thl=en&tz=UTC",
        ".youtube.com\tTRUE\t/\tTRUE\t" + (NOW + 7200) + "\tVISITOR_INFO1_LIVE\tvisitor",
        ".youtube.com\tTRUE\t/\tTRUE\t0\tYSC\tnew-session"));

    NetscapeCookieFile.MergeResult result = stored.merge(ytDlpDump.cookies(),
        NetscapeCookieFile.rotatableCookieNames(), NOW);
    String merged = result.file().serialize();

    assertTrue(result.changed());
    assertEquals(List.of("__Secure-1PSIDTS"), result.updatedNames());
    assertTrue(merged.contains("#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tLOGIN_INFO\tlogin-value"));
    assertEquals("sapisid-value", findCookie(result.file(), "SAPISID").value());
    assertTrue(merged.startsWith("# Netscape HTTP Cookie File\n# Generated by the user"));
    assertFalse(result.file().hasCookie("PREF"));
    assertFalse(result.file().hasCookie("VISITOR_INFO1_LIVE"));
    assertEquals("refreshed-by-ytdlp", findCookie(result.file(), "__Secure-1PSIDTS").value());
  }

  private NetscapeCookie cookie(String domain, String name, String value, long expiresAt) {
    return new NetscapeCookie(domain, true, "/", true, expiresAt, name, value, false);
  }

  private NetscapeCookie findCookie(NetscapeCookieFile file, String name) {
    return file.cookies().stream()
        .filter(cookie -> cookie.name().equals(name))
        .findFirst()
        .orElseThrow(() -> new AssertionError("cookie not found: " + name));
  }
}
